updated backend_yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -403,7 +403,59 @@ jobs:
       - revert-migrations:
           workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
 
-
+  smoke-test:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            sudo apt update
+            sudo apt install -y awscli
+            sudo apt install -y python3 ansible
+            sudo apt install -y curl
+            sudo apt upgrade -y
+            aws --version
+            
+      - run:
+          name: Frontend smoke test.
+          command: |
+            
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com"
+              echo ${URL}
+            if curl -s ${URL} | grep "Welcome"
+            then
+              echo "Successful front-end Smoke-test but failing intentionally"
+              # exit 1
+            else
+              echo "Unsuccessful front-end Smoke-test"
+              exit 1
+            fi
+      - run:
+          name: Backend smoke test.
+          command: |
+            
+            export BACKEND_IP=$(aws ec2 describe-instances \
+                --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                --output text)
+              export API_URL="http://${BACKEND_IP}:3030"
+              echo "API_URL = ${API_URL}"
+              sleep 60
+              if curl "${API_URL}/api/status" | grep "ok"
+              then
+                echo SUCCESS
+                exit 0
+              else
+                echo FAIL
+                exit 1
+              fi
+      
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
   
 
 
